"""
Schemas Package for ThinkFlow Studio.

Contains Pydantic schema validation models mapping user requests,
agent inputs/outputs, and serialization layers.

TODOs:
    - [ ] Create specialized schemas matching Google ADK structured guidelines.
    - [ ] Add Gherkin-style Acceptance Criteria parsing rules to the feature schemas.
"""

from pydantic import BaseModel, Field


class FeatureItemSchema(BaseModel):
    """
    Structured feature item extracted from ideas.
    """
    id: str = Field(description="Unique incremental key of the feature")
    title: str = Field(description="Name description of the feature")
    description: str = Field(description="Gherkin syntax descriptive feature task")
    complexity: str = Field(description="Sizing score metrics: EASY, MEDIUM, HARD")
    dependencies: list[str] = Field(
        default_factory=list, description="IDs of pre-requisite features"
    )


class AnalysisOutputSchema(BaseModel):
    """
    Structured analysis report generated by the Analyzer agent.
    """
    domain: str = Field(description="Classified context categories")
    summary: str = Field(description="Detailed overview of the idea")
    features: list[FeatureItemSchema] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)


class SessionStartRequest(BaseModel):
    """
    Payload required to bootstrap a session sequence.
    """
    raw_idea: str = Field(min_length=10, description="Raw input ideas prompt")
    domain_hint: str | None = Field(default=None)
