"""
Orchestration and execution plan schemas for the Coordinator Agent.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class AgentTask(BaseModel):
    """
    A single task to be executed by a specialized agent.
    """
    task_id: str = Field(description="Unique identifier for the task.")
    target_agent: str = Field(description="The string identifier of the agent to invoke (e.g., 'analyzer', 'critic').")
    instruction: str = Field(description="Specific instructions for the agent.")
    input_payload: Dict[str, Any] = Field(default_factory=dict, description="Context variables required by the agent.")
    dependencies: List[str] = Field(default_factory=list, description="List of task_ids that must complete before this task.")

class ExecutionPlan(BaseModel):
    """
    The structured plan generated by the Coordinator.
    """
    plan_id: str = Field(description="Unique identifier for this plan.")
    tasks: List[AgentTask] = Field(default_factory=list, description="Ordered or parallel tasks to execute.")
    estimated_steps: int = Field(description="Total number of tasks.")

class WorkflowState(BaseModel):
    """
    Tracks the execution status of an overall session plan.
    """
    session_id: str
    plan: Optional[ExecutionPlan] = None
    completed_tasks: List[str] = Field(default_factory=list)
    failed_tasks: List[str] = Field(default_factory=list)
    results: Dict[str, Any] = Field(default_factory=dict)
    status: str = Field(default="pending", description="pending, running, completed, failed")
